config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  get "/sign_up" => "clearance/users#new", :as => "sign_up"
  get "/confirm_email/:token" => "email_confirmations#update", :as => "confirm_email"

  get "search", to: "search#index"
  get "timeline", to: "timeline#index"
  get "notifications", to: "notifications#index"
  root to: "home#index"

  get "home/index"

  resources :users, only: [:show, :edit, :update] do
    resources :friends_posts, only: [:new, :create]
  end
  resources :posts
  resources :comments, except: [:show, :new]
  resources :invites, except: [:show]
  resources :post_images, only: [:create, :destroy]
  resources :user_profile_images, only: [:create, :destroy]
  resources :reactions, only: [:create, :destroy]
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def index
    @sent_invites = current_user.sent_invitations
    @received_invites = current_user.received_invitations
  end

  def create
    @related = User.find(relationship_params.fetch(:related_id))
    @relationship = Relationship.new(
      relatee: current_user,
      related: @related,
      accepted: false
    )
    if @relationship.save
      Notification.create!(
        user: @related,
        initiator: current_user,
        target: current_user,
        message: "You received a friend request from #{current_user.full_name}"
      )
      flash.notice = "An invitation has been sent"
    else
      flash.alert = "There was a problem sending this invite"
    end
    redirect_to @related
  end

  def update
    @relationship = Relationship.find(params[:id])
    @relationship.accepted = true
    if @relationship.save
      Notification.create!(
        user: @relationship.relatee,
        initiator: current_user,
        target: @relationship.related,
        message: "Your request has been accepted by #{@relationship.relatee.full_name}"
      )
      flash.notice = "You accepted the invitation!"
    else
      flash.alert = "There was a problem accepting the invitation"
    end
    redirect_back(fallback_location: timeline_path)
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    if @relationship.destroy
      flash.notice = if current_user == @relationship.relatee
        "This invite has been revoked"
      else
        "This invite has been declined"
      end
    else
      flash.alert = "There was a problem revoking this invite"
    end
    redirect_back(fallback_location: timeline_path)
  end

  private

  def relationship_params
    params.require(:relationship).permit(:related_id)
  end
end

app/views/invites/index.html.haml
.container.lg.mx-auto.px-5.min-h-screen.py-5
  .min-h-screen
    %h3.text-3xl Invites
    %h4.text-2xl Received Invites
    - @received_invites.each do |invite|
      .received-invitation.px-4.py-4
      .received-invitation.px-4.py-4.h-20.flex.justify-between{ class: cycle("", "bg-gray-400")}
        .info
          = image_tag(url_for(invite.relatee.post_thumbnail_url), class: "h-12 rounded-full inline-block mr-4")
          %span= invite.relatee.full_name
        .actions
          = link_to "Decline", invite_path(invite), method: :delete, class: "inline-block py-2 px-4 border-2 border-red-800 rounded-lg text-red-800 font-bold"
          = link_to "Accept", invite_path(invite), method: :patch, class: "inline-block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
    %h4.text-2xl Sent Invites
    - @sent_invites.each do |invite|
      .sent-invitation.px-4.py-4.h-20.flex.justify-between{ class: cycle("", "bg-gray-400")}
        .info
          = image_tag(url_for(invite.related.post_thumbnail_url), class: "h-12 rounded-full inline-block mr-4")
          %span= invite.related.full_name
        .actions
          = link_to "Cancel", invite_path(invite), method: :delete, class: "inline-block py-2 px-4 border-2 border-red-800 rounded-lg text-red-800 font-bold"