config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  get "/sign_up" => "clearance/users#new", :as => "sign_up"
  get "/confirm_email/:token" => "email_confirmations#update", :as => "confirm_email"

  get "search", to: "search#index"
  get "timeline", to: "timeline#index"
  get "notifications", to: "notifications#index"
  root to: "home#index"

  get "home/index"

  resources :users, only: [:show, :edit, :update] do
    resources :friends_posts, only: [:new, :create]
  end
  resources :posts
  resources :comments, except: [:show, :new]
  resources :invites, except: [:show]
  resources :post_images, only: [:create, :destroy]
  resources :user_profile_images, only: [:create, :destroy]
  resources :reactions, only: [:create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :bigint           not null, primary key
#  body         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  recipient_id :bigint
#  user_id      :bigint           not null
#
# Indexes
#
#  index_posts_on_recipient_id  (recipient_id)
#  index_posts_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (recipient_id => users.id)
#  fk_rails_...  (user_id => users.id)
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User", required: false
  has_many :images, as: :imageable, dependent: :destroy
  has_many :reactions, as: :content, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  accepts_nested_attributes_for :images

  def preview_image
    images.first.image.variant(resize_to_fill: [1000, 220, {gravity: "Center"}])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = current_user
    @post = @user.posts.build
    @post.images.build
  end

  def show
    @post = Post.find(params[:id])
    @comment = current_user.comments.build
    @comments = @post.comments.order(created_at: :desc)
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    unassigned_images = current_user.images.unassigned
    if @post.save && unassigned_images.update_all(imageable_id: @post.id, imageable_type: "Post")
      flash.notice = "Your post has been created."
      redirect_to @user
    else
      flash.alert = "There was a problem saving your post."
      render "new"
    end
  end

  def edit
    @user = current_user
    @post = @user.posts.find(params[:id])
  end

  def update
    @user = current_user
    @post = @user.posts.find(params[:id])
    if @post.update(post_params)
      flash.notice = "Your post has been updated."
      redirect_to @user
    else
      flash.alert = "There was a problem saving your post."
      render "edit"
    end
  end

  def destroy
    @user = current_user
    @post = @user.posts.find(params[:id])
    if @post.destroy
      flash.notice = "Your post has been deleted."
    else
      flash.alert = "Your post has not been deleted."
    end
    redirect_to @user
  end

  private

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/views/shared/post/_index.haml
.mb-4.shadow-lg
  - if post.images.present?
    = link_to(image_tag(url_for(post.preview_image), class: "preview-image rounded-t"), post_path(post))
    .bg-gray-300.border-r.border-l.border-dotted.border-gray-600.flex
      = render partial: "shared/post/post_body", locals: {post: post}
    = render partial: "shared/post/post_footer", locals: {post: post}
  - else
    .bg-gray-300.border-t.border-r.border-l.border-dotted.border-gray-600.rounded-t.flex
      = render partial: "shared/post/post_body", locals: {post: post}
    = render partial: "shared/post/post_footer", locals: {post: post}

app/views/shared/post/_post_body.haml
- if post.user.post_thumbnail_url.present?
  .post-user-image.w-24.flex-none.px-5.py-5
    = image_tag(post.user.post_thumbnail_url, class: "rounded-full")
.post-info.px-5.py-5
  .post-body-header.mb-3
    = link_to("#{post.user.full_name}", user_path(post.user), class: "text-xs inline underline")
    %span.text-xs= " posted #{time_ago_in_words(post.created_at)} ago"
  %p= post.body

app/views/shared/post/_post_footer.haml
.bg-gray-400.px-5.rounded-b.border.border-dotted.border-gray-600.py-2.flex.justify-between
  .actions
    = link_to("#{pluralize(post.comments.size, "Comment")}", post_path(post), class: "underline")
  .actions.flex
    - if policy(post).update?
      = link_to(inline_svg_tag("icons/edit.svg"), edit_post_path(post), class: "mr-2")
      = link_to(inline_svg_tag("icons/trash-2.svg"), post_path(post), class: "text-sm text-red-800", id: "delete-post", method: :delete)
      %span.ml-6= post.reactions.size
      = inline_svg_tag("icons/thumbs-up.svg", class: "ml-2") 
    - else
      %span.mr-2= post.reactions.size
      - if current_user.reaction_to(post)
        = link_to(inline_svg_tag("icons/thumbs-up.svg", class: "text-green-800"), reaction_path(current_user.reaction_to(post)), method: :delete, id: "remove-like" )
      - else
        = link_to(inline_svg_tag("icons/thumbs-up.svg"), reactions_path(params: { reaction: { sentiment: :like, content_type: "Post", content_id: post.id }}), method: :post, id: "like" )