config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  get "/sign_up" => "clearance/users#new", :as => "sign_up"
  get "/confirm_email/:token" => "email_confirmations#update", :as => "confirm_email"

  get "search", to: "search#index"
  get "timeline", to: "timeline#index"
  get "notifications", to: "notifications#index"
  root to: "home#index"

  get "home/index"

  resources :users, only: [:show, :edit, :update] do
    resources :friends_posts, only: [:new, :create]
  end
  resources :posts
  resources :comments, except: [:show, :new]
  resources :invites, except: [:show]
  resources :post_images, only: [:create, :destroy]
  resources :user_profile_images, only: [:create, :destroy]
  resources :reactions, only: [:create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :bigint           not null, primary key
#  birthday                 :date
#  confirmation_token       :string(128)
#  email                    :string           not null
#  email_confirmation_token :string           default(""), not null
#  email_confirmed_at       :datetime
#  encrypted_password       :string(128)      not null
#  first_name               :string
#  gender                   :integer
#  last_name                :string
#  remember_token           :string(128)      not null
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_users_on_email           (email)
#  index_users_on_remember_token  (remember_token)
#

class User < ApplicationRecord
  include Clearance::User

  has_many :posts, dependent: :destroy
  has_many :posts_from_friends, foreign_key: :recipient_id, dependent: :destroy, class_name: "Post"
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :initiated_relationships, -> { where(accepted: true) }, foreign_key: :relatee_id, dependent: :destroy, class_name: "Relationship"
  has_many :accepted_relationships, -> { where(accepted: true) }, foreign_key: :related_id, dependent: :destroy, class_name: "Relationship"
  has_many :sent_invitations, -> { where(accepted: false) }, foreign_key: :relatee_id, class_name: "Relationship"
  has_many :received_invitations, -> { where(accepted: false) }, foreign_key: :related_id, class_name: "Relationship"
  has_many :invited_friends, through: :sent_invitations, source: :related
  has_many :initiated_friends, through: :initiated_relationships, source: :related, class_name: "User"
  has_many :accepted_friends, through: :accepted_relationships, source: :relatee, class_name: "User"
  has_many :initiated_friends_posts, through: :initiated_friends, source: :posts
  has_many :accepted_friends_posts, through: :accepted_friends, source: :posts
  has_one :profile_image,
    as: :imageable,
    dependent: :destroy,
    class_name: "Image"
  has_many :notifications

  enum gender: {male: 0, female: 1}

  def self.searchable_columns
    [:first_name, :last_name]
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def profile_image_url
    profile_image&.image&.variant(resize_to_fill: [385, 289, {gravity: "Center"}])
  end

  def post_thumbnail_url
    profile_image&.image&.variant(resize_to_fill: [240, 240, {gravity: "Center"}])
  end

  def friends_with?(user)
    friends_ids.include?(user.id)
  end

  def invited?(user)
    invited_friends.where(id: user.id).exists?
  end

  def friends_posts
    Post.where(user_id: friends_ids.push(id)).order(created_at: :desc)
  end

  def reaction_to(content)
    reactions.where(content: content).first
  end

  def friends
    User.where(id: friends_ids)
  end

  def confirm_email!
    self.email_confirmed_at = Time.current
    save!
  end

  def confirmed?
    email_confirmed_at.present?
  end

  def has_unread_notifications?
    notifications.unread.exists?
  end

  private

  def friends_ids
    relationships.pluck(:related_id, :relatee_id).flatten.uniq
  end

  def relationships
    initiated_relationships.or(accepted_relationships)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.or(@user.posts_from_friends).order(created_at: :desc)
  end

  def create
    @user = User.new(user_params)
    @user.email_confirmation_token = Clearance::Token.new

    if @user.save!
      UserMailer.with(@user).registration_confirmation.deliver_later
      flash.notice = "Your profile has been created. Please confirm your email to login!"
      redirect_back_or sign_in_path
    else
      render template: "users/new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash.notice = "Your profile has been updated."
      redirect_to @user
    else
      flash.alert = "There was a problem saving your profile."
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthday, :gender, :email, :password)
  end
end

app/views/users/_form.haml
.text-field
  = form.label :email
  = form.text_field :email, type: 'email'
.password-field
  = form.label :password
  = form.password_field :password

app/views/users/edit.haml
.container.lg.mx-auto.px-5.h-screen.py-5
  .flex.justify-between.content-center.mb-4
    %h3.text-3xl Edit User
    = link_to "Back to Profile", user_path(@user), class: "bg-gray-300 block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
  = simple_form_for @user do |f|
    = f.input :first_name,
      placeholder: "Johnny",
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded w-full outline-none" }
    = f.input :last_name,
      placeholder: "Appleseed",
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded w-full outline-none" }
    = f.input :birthday,
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded outline-none" },
      label_html: { class: "block" },
      start_year: Date.today.year - 110,
      end_year: Date.today.year - 18,
      default: Date.today
    = f.input :gender,
      collection: User.genders.keys,
      label_html: { class: "block"},
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded outline-none"}
    = f.submit "Update Profile", class: "block w-full mt-4 py-2 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold bg-gray-300"

app/views/users/new.haml
#clearance.sign-in.flex.h-screen
  %div.flex-1.flex.h-screen.bg-indigo-300
    .m-auto
      %h2= t(".title")
  %div.flex-1.flex.h-screen.bg-indigo-800
    .m-auto
      .shadow-lg
        .m-auto.pt-10.px-16.bg-gray-100.rounded-t-lg.pb-6.border-b.border-gray-600
          %h4.text-center.text-indigo-800.text-2xl.pb-4= t(".heading")
          = form_for @user do |form|
            .text-field.py-3
              = form.text_field :email, type: 'email', class: "bg-indigo-200 border-b-2 border-indigo-300 text-indigo-800 p-3 rounded w-full outline-none"
            .password-field.py-3
              = form.password_field :password, class: "bg-indigo-200 border-b-2 border-indigo-300 text-indigo-800 p-3 rounded w-full outline-none"
            .submit-field
              = form.button t(".submit_button"), class: "block w-full mt-4 py-2 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
        .m-auto.h-16.px-16.rounded-b-lg.bg-gray-300.flex
          .m-auto.align-center
            = link_to t(".sign_in"), sign_in_path, class: "text-indigo-800"
            = " | "
            = link_to t(".forgot_password"), new_password_path, class: "text-indigo-800"

app/views/users/show.haml
.container.lg.mx-auto.px-5.min-h-screen.py-5.grid.grid-cols-3.gap-4
  .min-h-screen.flex.flex-col.mr-4.col-span-1
    .user-header.flex.justify-between.mb-4
      %h3.text-3xl.inline-block= @user.full_name
      - if policy(@user).update?
        = link_to(inline_svg_tag("icons/edit.svg"), edit_user_path(@user), class: "text-sm self-end mb-1")
    - if policy(@user).update?
      .user-image-uploader.bg-gray-400.mt-4border.border-dotted.border-gray-600.rounded-t{ data: { profile_image: url_for(@user.profile_image_url), id: @user.profile_image&.id }}
    - elsif @user.profile_image.blank?
      .bg-gray-400.border.border-dotted.border-gray-600.rounded-t.h-56.flex.items-center.justify-center
        = inline_svg_tag("icons/user.svg")
    - else
      .bg-gray-400.mt-4border.border-dotted.border-gray-600.rounded-t
        = image_tag(@user.profile_image_url)

    .user-info.bg-gray-300.px-5.py-5.border-b.border-r.border-l.border-dotted.border-gray-600.rounded-b.flex.justify-between
      .traits
        %span= @user.gender&.titleize
      .relationship.flex.flex-row-reverse
        - if current_user.friends_with?(@user)
          %span.text-xs Friends
        - elsif current_user.invited?(@user)
          %span.text-xs Invited
        - elsif !(@user == current_user)
          = link_to(inline_svg_tag("icons/plus-circle.svg"), invites_path(params: { relationship: { related_id: @user.id } }), method: :post, id: "add-friend" )

    #my-elm-container
  .col-span-2
    .flex.justify-between.content-center.mb-4
      %h3.text-3xl= "Posts"
      = link_to "Post on #{@user.first_name}'s Page", new_user_friends_post_path(@user), class: "bg-gray-300 block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
    .mb-4
      - @posts.each do |post|
        = render partial: "shared/post/index", locals: {post: post}
- content_for :tail_scripts do
  = javascript_pack_tag "post_gallery"
  = javascript_pack_tag "user_image_uploader"