config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  get "/sign_up" => "clearance/users#new", :as => "sign_up"
  get "/confirm_email/:token" => "email_confirmations#update", :as => "confirm_email"

  get "search", to: "search#index"
  get "timeline", to: "timeline#index"
  get "notifications", to: "notifications#index"
  root to: "home#index"

  get "home/index"

  resources :users, only: [:show, :edit, :update] do
    resources :friends_posts, only: [:new, :create]
  end
  resources :posts
  resources :comments, except: [:show, :new]
  resources :invites, except: [:show]
  resources :post_images, only: [:create, :destroy]
  resources :user_profile_images, only: [:create, :destroy]
  resources :reactions, only: [:create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :bigint           not null, primary key
#  body         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  recipient_id :bigint
#  user_id      :bigint           not null
#
# Indexes
#
#  index_posts_on_recipient_id  (recipient_id)
#  index_posts_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (recipient_id => users.id)
#  fk_rails_...  (user_id => users.id)
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: "User", required: false
  has_many :images, as: :imageable, dependent: :destroy
  has_many :reactions, as: :content, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  accepts_nested_attributes_for :images

  def preview_image
    images.first.image.variant(resize_to_fill: [1000, 220, {gravity: "Center"}])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @user = current_user
    @post = @user.posts.build
    @post.images.build
  end

  def show
    @post = Post.find(params[:id])
    @comment = current_user.comments.build
    @comments = @post.comments.order(created_at: :desc)
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    unassigned_images = current_user.images.unassigned
    if @post.save && unassigned_images.update_all(imageable_id: @post.id, imageable_type: "Post")
      flash.notice = "Your post has been created."
      redirect_to @user
    else
      flash.alert = "There was a problem saving your post."
      render "new"
    end
  end

  def edit
    @user = current_user
    @post = @user.posts.find(params[:id])
  end

  def update
    @user = current_user
    @post = @user.posts.find(params[:id])
    if @post.update(post_params)
      flash.notice = "Your post has been updated."
      redirect_to @user
    else
      flash.alert = "There was a problem saving your post."
      render "edit"
    end
  end

  def destroy
    @user = current_user
    @post = @user.posts.find(params[:id])
    if @post.destroy
      flash.notice = "Your post has been deleted."
    else
      flash.alert = "Your post has not been deleted."
    end
    redirect_to @user
  end

  private

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/views/posts/_comment.haml
.comment.mb-4.shadow
  .bg-gray-300.border-t.border-r.border-l.border-dotted.border-gray-600.rounded-t.flex
    - if comment.user.post_thumbnail_url.present?
      .comment-user-image.w-24.flex-none.px-5.py-5
        = image_tag(comment.user.post_thumbnail_url, class: "rounded-full")
    .comment-info.px-5.py-5
      .comment-body-header.mb-3
        = link_to("#{comment.user.full_name}", user_path(comment.user), class: "text-xs inline underline")
        %span.text-xs= " commented #{time_ago_in_words(comment.created_at)} ago"
      %p= comment.body
  .bg-gray-400.px-5.rounded-b.border.border-dotted.border-gray-600.py-2.flex.flex-row-reverse
    .actions.flex
      - if policy(comment).destroy?
        = link_to(inline_svg_tag("icons/trash-2.svg"), comment_path(comment), class: "text-sm text-red-800", id: "remove-comment", method: :delete)
      - else
        %span.mr-2= comment.reactions.size
        - if current_user.reaction_to(comment)
          = link_to(inline_svg_tag("icons/thumbs-up.svg", class: "text-green-800"), reaction_path(current_user.reaction_to(comment)), method: :delete, id: "remove-like" )
        - else
          = link_to(inline_svg_tag("icons/thumbs-up.svg"), reactions_path(params: { reaction: { sentiment: :like, content_type: "Comment", content_id: comment.id }}), method: :post, id: "like" )

app/views/posts/edit.haml
.container.lg.mx-auto.px-5.h-screen.py-5
  .flex.justify-between.content-center.mb-4
    %h3.text-3xl Edit Post
    = link_to "Back to Profile", user_path(@user), class: "bg-gray-300 block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
  = simple_form_for @post do |f|
    = f.input :body,
      label: false,
      placeholder: "What's up?",
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded w-full outline-none" }
    = f.file_field :images,
      multiple: true,
      label: false
    = f.submit "Update Post", class: "block w-full mt-4 py-2 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold bg-gray-300"

app/views/posts/new.haml
.container.lg.mx-auto.px-5.h-screen.py-5
  .flex.justify-between.content-center.mb-4
    %h3.text-3xl New Post
    = link_to "Back to Profile", user_path(@user), class: "bg-gray-300 block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
  = simple_form_for @post do |f|
    = f.input :body,
      label: false,
      placeholder: "What's up?",
      input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded w-full outline-none" }
    .file-selector
    = f.submit "Create Post", class: "block w-full mt-4 py-2 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold bg-gray-300"
- content_for :tail_scripts do
  = javascript_pack_tag "post_form"

app/views/posts/show.haml
.container.lg.mx-auto.px-5.h-screen.py-5
  .flex.justify-between.content-center.mb-4
    %h3.text-3xl  Post
    = link_to "#{@post.user.first_name}'s Profile", user_path(@post.user), class: "bg-gray-300 block py-2 px-4 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold"
  .gallery.flex.flex-row
    - @post.images.each do |image|
      = image_tag(url_for(image.gallery_preview), class: "preview-image rounded-t mr-4 mb-4")
  .post-content
    %p= @post.body
  .new-comment.mt-4
    = simple_form_for @comment do |f|
      = f.input :body, placeholder: "Do you have something to say on the Internet?", input_html: { class: "bg-gray-200 border border-gray-500 text-indigo-800 p-3 rounded w-full outline-none" }, label: "Comment"
      = f.input :commentable_type, as: :hidden, input_html: { value: "Post" }
      = f.input :commentable_id, as: :hidden, input_html: { value: @post.id }
      = f.submit "Submit", class: "block w-full mt-4 py-2 border-2 border-indigo-800 rounded-lg text-indigo-800 font-bold bg-gray-300"
  .comments.mt-4
    %h4 Comments
    - @comments.each do |comment|
      = render partial: "comment", locals: {comment: comment}